import { lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createProjectContext } from "@codememory/shared";

/** Generates a project-scoped entry; never edits global client settings. */
export async function connectCodex(root: string, executable: string, entry: string, write = false) {
  const context = await createProjectContext(root);
  const directory = resolve(context.canonicalRoot, ".codex");
  const path = resolve(directory, "config.toml");
  const config = [
    "# Generated by CodeMemory. Machine-local absolute paths; do not publish this file.",
    "[mcp_servers.integra_code_memory]",
    `command = ${JSON.stringify(executable)}`,
    `args = ${JSON.stringify([entry, "mcp", "--project", context.canonicalRoot, "--auto-index", "--watch"])}`,
    `cwd = ${JSON.stringify(context.canonicalRoot)}`,
    'env_vars = ["DATABASE_URL"]',
    "startup_timeout_sec = 30",
    "tool_timeout_sec = 60",
    "enabled = true",
    "",
  ].join("\n");
  if (!write) return { path, config, written: false };
  const info = await lstat(directory).catch((error: NodeJS.ErrnoException) => {
    if (error.code !== "ENOENT") throw error;
    return null;
  });
  if (info && (!info.isDirectory() || info.isSymbolicLink()))
    throw new Error("Project .codex must be a regular directory");
  await mkdir(directory, { recursive: true });
  try {
    await writeFile(path, config, { flag: "wx", mode: 0o600 });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
    if (!(await lstat(path)).isFile() || (await lstat(path)).isSymbolicLink())
      throw new Error("Existing Codex config must be a regular file");
    if ((await readFile(path, "utf8")) !== config)
      throw new Error(
        "Existing Codex configuration differs. Preview the entry and merge it manually; nothing was overwritten.",
      );
  }
  return { path, config, written: true };
}
if (import.meta.main && process.argv[1]?.endsWith("connect-codex.ts")) {
  const args = process.argv.slice(2);
  if (!args[0] || args.length > 2 || (args[1] && args[1] !== "--write"))
    throw new Error("Usage: bun run connect:codex /absolute/project [--write]");
  console.log(
    JSON.stringify(
      await connectCodex(
        args[0],
        process.execPath,
        fileURLToPath(new URL("../apps/cli/src/index.ts", import.meta.url)),
        args[1] === "--write",
      ),
      null,
      2,
    ),
  );
}
